fixtures:
  repositories:
    runit:
      repo: "git://github.com/steakknife/steakknife-runit.git"
      ref: "0.1.1"
    mysql:
      repo: 'git://github.com/puppetlabs/puppetlabs-mysql.git'
      ref: '0.9.0'
    postgresql:
      repo: 'git://github.com/puppetlabs/puppet-postgresql.git'
      ref: "2.5.0"
    mongodb: 'git://github.com/puppetlabs/puppetlabs-mongodb.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat: 'git://github.com/ripienaar/puppet-concat.git'
    nginx: 'git://github.com/BenoitCattie/puppet-nginx.git'
    rbenv: 'git://github.com/dima-exe/puppet-rbenv.git'
    backup: 'git://github.com/dima-exe/puppet-backup.git'
  symlinks:
    deploy: "#{source_dir}"
