rvm:
  - 1.8.7
  - 1.9.3
branches:
  only:
    - master
env:
  - PUPPET_GEM_VERSION="3.1"
  - PUPPET_GEM_VERSION="3.2"
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"

bundler_args: ""
