name    'dmexe-deploy'
version '0.2.1'
source 'http://github.com/dima-exe/puppet-deploy'
author 'Dmitry Galinsky'
license 'MIT'
summary 'Puppet deploy management for applications, mysql and postgresql databases'
project_page 'http://github.com/dima-exe/puppet-deploy'

dependency 'puppetlabs/stdlib', '>= 0'
dependency 'puppetlabs/postgresql', '= 2.5.0'
