name    'dmexe-deploy'
version '0.2.13'
source 'http://github.com/dima-exe/puppet-deploy'
author 'Dmitry Galinsky'
license 'MIT'
summary 'Puppet deploy management for applications, mysql and postgresql databases'
project_page 'http://github.com/dima-exe/puppet-deploy'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/postgresql', '= 2.5.0'
dependency 'puppetlabs/mysql',      '= 0.9.0'
dependency 'steakknife/runit',      '= 0.1.1'
