Vagrant.configure("2") do |c|
  c.vm.define 'main.foo.vm' do |v|
    v.vm.hostname = 'main.foo.vm'
    v.vm.box = 'ubuntu-server-12042-x64-vbox4210-nocm'
    v.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box'
    v.vm.provider 'virtualbox' do |vbox|
      vbox.customize ['modifyvm',:id,'--macaddress1','080027700571']
    end
  end
end
